init:
  image: 192.168.0.28:5000/redis 
  link:
  - redis
  environment:
  - REDIS_NODE_PORT:${redis_port}
  - REDIS_SCALE:${redis_scale}
  - REDIS_REPLICATION:${rep_factor}
  labels:
   io.rancher.container.start_once: true
  command: /redis/bootstrap.sh init

redis:
  environment:
  - REDIS_NODE_PORT:${redis_port}
  - REDIS_SCALE:${redis_scale}
  - REDIS_REPLICATION:${rep_factor}
  image: 192.168.0.28:5000/redis
