master:
  image: 192.168.0.28:5000/redis-cluster:latest
  restart: always
  stdin_open: true
  tty: true
  environment:
    - SERVICE_NAME=${instance_name}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  ports:
    - "6379:6379"
    - "16379:16379"
  volumes:
    - /data/master:/data

slave:
  image: 192.168.0.28:5000/redis-cluster:latest
  restart: always
  stdin_open: true
  tty: true
  environment:
    - SERVICE_NAME=${instance_name}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  ports:
    - "6389:6379"
    - "16389:16379"
  volumes:
    - /data/slave:/data

conf:
  image: 192.168.0.28:5000/redis-cluster:latest
  environment:
    - SERVICE_NAME=${instance_name}
  labels:
    io.rancher.container.start_once: true
  entrypoint: ["/usr/local/bin/init.sh"] 
