version: '2'
.catalog:
  name: redis cluster
  version: 1.0
  description: |
    Redis cluster for rancher

services:
  master:
    scale: 3 
    retain_ip: true
    health_check:
      port: 6379
      interval: 5000
      unhealthy_threshold: 3
      request_line: ''
      healthy_threshold: 2
      response_timeout: 5000

  slave:
    scale: 3
    retain_ip: true
    health_check:
      port: 6379
      interval: 5000
      unhealthy_threshold: 3
      request_line: ''
      healthy_threshold: 2
      response_timeout: 5000

